INSERT INTO USER_ADDRESS (`USER_ID`, `ADDRESS_ROWID`) VALUES (1,1);
INSERT INTO USER_ADDRESS (`USER_ID`, `ADDRESS_ROWID`) VALUES (2,2);
INSERT INTO USER_ADDRESS (`USER_ID`, `ADDRESS_ROWID`) VALUES (3,3);
INSERT INTO USER_ADDRESS (`USER_ID`, `ADDRESS_ROWID`) VALUES (4,4);
INSERT INTO USER_ADDRESS (`USER_ID`, `ADDRESS_ROWID`) VALUES (5,5);
INSERT INTO USER_ADDRESS (`USER_ID`, `ADDRESS_ROWID`) VALUES (6,6);
INSERT INTO USER_ADDRESS (`USER_ID`, `ADDRESS_ROWID`) VALUES (7,7);