management:
  endpoints:
    web:
      base-path: /status
  server:
    port: 8081
server:
  servlet:
    context-path: /tomtom/e_commerce
  port: 8001
  max-http-header-size: 10000000
spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: <emailid>
    password: <password>
    protocol: smtp
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: sa
    password:
  h2:
    console:
      enabled: true
  main:
    web-application-type: servlet
  sql:
    init:
      mode: always
      data-locations: classpath:sql/dml/address.sql,classpath:sql/dml/cart.sql,classpath:sql/dml/user.sql,classpath:sql/dml/user_address.sql,classpath:sql/dml/product.sql,classpath:sql/dml/product_color.sql,classpath:sql/dml/product_user_gender.sql
      platform: h2
  jpa:
    defer-datasource-initialization: true
    show-sql: false
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
  security:
    user:
      name: tomtom
      password: password
      roles: USER